### ISSUE TITLE
it could not work when when use npm run build

### ISSUE THREAD

**Issue by moliyu** [antfu/unplugin-vue2-script-setup#54] opened 2021-10-18 02:36 UTC
i have just cloned this repo. when it in development, it works well. But when i build it and copy the dist to nginx.it didn't work as expect

![image](https://user-images.githubusercontent.com/41667833/137660510-e95b9c45-4e84-4382-965a-f99e38a19f15.png)
![image](https://user-images.githubusercontent.com/41667833/137660557-76ec8cf3-616f-4656-ad90-922fea07ff3b.png)

**Comment by antfu** [comment] 2021-11-01 23:08
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-11-01 23:08 UTC
