### ISSUE TITLE
script setup在transform后，终端eslint报错Extra semicolon

### ISSUE THREAD

**Issue by catNano** [antfu/unplugin-vue2-script-setup#90] opened 2021-12-27 10:11 UTC
script setup的transform顺序有问题，代码应该在eslint校验后，再transform

**Comment by antfu** [comment] 2021-12-27 15:45
I would not recommend using eslint at the building/bundling phase.

**Comment by catNano** [comment] 2021-12-28 01:45
It is an error reported after Vue cli is started
![image](https://user-images.githubusercontent.com/42427796/147518675-a10673a0-ae1a-4d04-b82d-d91ba4e7b8c3.png)

**Comment by xiaoxiangmoe** [comment] 2022-01-23 07:45
@catNano 你能给我一个最小可复现的 demo 吗？我看看怎么配。

**Comment by xiaoxiangmoe** [comment] 2022-03-03 06:03
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by xiaoxiangmoe** 2022-03-03 06:03 UTC
