### ISSUE TITLE
 [vite] Internal server error: $ can only be used as the initializer of a variable declaration.

### ISSUE THREAD

**Issue by 949054042** [antfu/unplugin-vue2-script-setup#97] opened 2022-01-11 03:40 UTC
how to reolve this question, thanks

**Comment by antfu** [comment] 2022-01-11 19:37
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-01-11 19:37 UTC
