### ISSUE TITLE
props defined by withDefaults and defineProps , use props in template have warning

### ISSUE THREAD

**Issue by ethnft** [antfu/unplugin-vue2-script-setup#53] opened 2021-10-16 06:08 UTC
![image](https://user-images.githubusercontent.com/91170597/137575749-4fc51c92-dfa9-4cee-a022-e36e07e85d53.png)
![image](https://user-images.githubusercontent.com/91170597/137575754-3e94cdb7-e437-4274-8e71-dd336e94fa61.png)

**Comment by ethnft** [comment] 2021-10-16 06:22
use reactive or ref  variable in template have correct info ,It was normal until I reinstalled node_modules

**Comment by antfu** [comment] 2021-11-01 23:08
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-11-01 23:08 UTC
