### ISSUE TITLE
Script setup doesn't unpack refs in template?

### ISSUE THREAD

**Issue by IAmRGroot** [antfu/unplugin-vue2-script-setup#58] opened 2021-10-23 16:45 UTC
Hi, I've just setup script setup in vue2 using this package. I'm noticing Typescript doesn't unpack the setup defined refs in the template, giving my this error:

![image](https://user-images.githubusercontent.com/8398505/138564663-b6ef472b-f58f-453c-b331-1af06ddfce4b.png)

The code works fine even with the error. Did I forgot to do something? 

I followed all the steps in the README. I am using Volar and this is my current tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "noUnusedLocals": true,
    "types": ["vite/client", "vuetify"],
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/vuetify/types",
      "./node_modules/vite/types",
      "./node_modules/unplugin-vue2-script-setup/types"
    ],
  },
  "vueCompilerOptions": {
    "experimentalCompatMode": 2
  },
  "include": [
    "resources/vue/src/**/*.ts",
    "resources/vue/src/**/*.d.ts",
    "resources/vue/src/**/*.tsx",
    "resources/vue/src/**/*.vue"
  ]
}
```

**Comment by rafaelytakei** [comment] 2021-11-01 19:56
Can't this be caused by `user` possibly being null?

**Comment by antfu** [comment] 2021-11-01 23:07
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-11-01 23:07 UTC
