### ISSUE TITLE
Vue Template 

### ISSUE THREAD

**Issue by stephenjason89** [antfu/unplugin-vue2-script-setup#89] opened 2021-12-27 05:34 UTC
Having errors with this
no errors if i am not using script setup tag
![image](https://user-images.githubusercontent.com/3810177/147437890-4778a921-f4a9-4a8e-a71a-2dc0fac9d824.png)
![image](https://user-images.githubusercontent.com/3810177/147437920-22f49099-91e2-44f3-a789-049c8c830aa2.png)

**Comment by stephenjason89** [comment] 2021-12-27 05:35
this will work if i add a comma after the first statement before showModal
but this conflicts with my prettier config

**Comment by xiaoxiangmoe** [comment] 2021-12-27 05:45
Can you provide a minimal reproduction that demonstrates the problem?

**Comment by xiaoxiangmoe** [comment] 2022-03-03 05:09
Can you provide a minimal reproduction that demonstrates the problem?

Maybe this was fixed in v0.10.0. I need add unit test for it.

**Comment by xiaoxiangmoe** [comment] 2022-03-04 05:27
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by xiaoxiangmoe** 2022-03-04 05:27 UTC
