### ISSUE TITLE
vite 3.0 启动报错[vite] Internal server error: $ can only be used as the initializer of a variable declaration.

### ISSUE THREAD

**Issue by TTcom** [antfu/unplugin-vue2-script-setup#147] opened 2022-07-27 06:08 UTC
### Describe the bug

vite 3.0 启动报错[vite] Internal server error: $ can only be used as the initializer of a variable declaration.
"vite": "v3.0.3",
"unplugin-vue2-script-setup": "^0.11.3"
use:
plugins: [
    ScriptSetup({
      reactivityTransform: true
    })
  ]

### Reproduction

npm run dev

### System Info

```Shell
windows10
chrome浏览器
nodejs v16.16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-07-27 06:23
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-07-27 06:23 UTC
