### ISSUE TITLE
Cannot set properties of undefined (setting'render').

### ISSUE THREAD

**Issue by maomincoding** [antfu/unplugin-vue2-script-setup#49] opened 2021-10-10 10:19 UTC
Hello, I encountered a problem when using Vue-cli to package into the production environment: Cannot set properties of undefined (setting'render').

The following are my few file configurations:

**package.json**
```json
{
  "name": "vue-cli",
  "private": true,
  "scripts": {
    "dev": "vue-cli-service serve",
    "build": "vue-tsc --noEmit && vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@vue/composition-api": "^1.2.4",
    "core-js": "^3.16.4",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.13",
    "@vue/cli-plugin-typescript": "^4.5.13",
    "@vue/cli-service": "^4.5.13",
    "typescript": "^4.4.2",
    "unplugin-vue2-script-setup": "workspace:*",
    "vue-template-compiler": "^2.6.14",
    "vue-tsc": "^0.3.0"
  }
}

```
**vue.config.js**
```js
/* eslint-disable @typescript-eslint/no-var-requires */

const ScriptSetup = require('unplugin-vue2-script-setup/webpack')

/**
 * @type {import('@vue/cli-service').ProjectOptions}
 */
module.exports = {
  configureWebpack: {
    plugins: [
      ScriptSetup({
        refTransform: true,
      }),
    ],
  },
  chainWebpack(config) {
    // disable type check and let `vue-tsc` handles it
    config.plugins.delete('fork-ts-checker')

    // disable cache for testing, you should remove this in production
    config.module.rule('vue').uses.delete('cache-loader')
    config.module.rule('js').uses.delete('cache-loader')
    config.module.rule('ts').uses.delete('cache-loader')
    config.module.rule('tsx').uses.delete('cache-loader')
  },
}

```

**Comment by antfu** [comment] 2021-10-10 10:48
Can you share a minimal reproduction? Thanks.

**Comment by maomincoding** [comment] 2021-10-10 11:43
Except for the changes to vue.config.js I mentioned above, nothing else has changed. If there is no problem in the development environment, this error will be reported in the production environment.

**Comment by maomincoding** [comment] 2021-10-10 11:45
I installed this version：unplugin-vue2-script-setup@0.6.11

**Comment by maomincoding** [comment] 2021-10-10 11:46
You can package it in the Vue-cli directory and put it in the production environment.

**Comment by maomincoding** [comment] 2021-10-11 00:04
I don't know why.

**Comment by maomincoding** [comment] 2021-10-11 23:55
Thanks,I'll consider upgrading your Node version to 14 or above.

**Comment by maomincoding** [comment] 2021-10-30 15:54
I'm the same as your probleml, and it hasn't been solved so far.

**Comment by antfu** [comment] 2021-11-01 23:07
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by maomincoding** [comment] 2021-11-02 01:47
Thanks.

**Comment by maomincoding** [comment] 2021-11-02 02:38
@antfu 
First of all, I am really sorry for not providing a detailed example.

The following is my system information：

  - System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 6.84 GB / 15.84 GB
  - Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  - Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
    Internet Explorer: 11.0.19041.1202

***
I have provided a link to the project, hoping to find the problem.

[https://github.com/maomincoding/vue2-cli-script-setup](https://github.com/maomincoding/vue2-cli-script-setup)

***

I found the problem like this: 

**1. First I run the command**
```bash
yarn
```
**2. Startup project**

```bash
yarn dev
```
There is no problem in the development environment.

![微信截图_20211102103510](https://user-images.githubusercontent.com/43904539/139777566-b2604485-dd40-4b19-bbdb-3cd843d1b467.png)

**3. Deploy to production environment**

```bash
yarn build
```
At this time, I found this error in the production environment.

![微信截图_20211102103202](https://user-images.githubusercontent.com/43904539/139777585-038d9c58-75f2-4c5c-96de-16161d77fe91.png)

***

The above is the problem I encountered, thanks.

**Comment by antfu** [comment] 2021-11-02 10:20
This plugin is conflicting with `thread-loader` for some reason, the current workaround is passing `parallel: false` in your `vue.config.js`

**Closed** 2021-11-02 10:19 UTC

**Comment by maomincoding** [comment] 2021-11-02 14:25
Thank you, the problem I encountered has been solved.

**Comment by yuanlin1995** [comment] 2022-12-19 08:53
> This plugin is conflicting with `thread-loader` for some reason, the current workaround is passing `parallel: false` in your `vue.config.js`

weather you have a plan to resolve it ?  
my project is too large, so, it's a big promote to build project. @antfu

**Comment by MiumMi** [comment] 2024-07-12 07:55
> > This plugin is conflicting with `thread-loader` for some reason, the current workaround is passing `parallel: false` in your `vue.config.js`
> 
> weather you have a plan to resolve it ? my project is too large, so, it's a big promote to build project. @antfu
How did you solve the problem? My project has the same problem @yuanlin1995
